### PR TITLE
Remove additionalProperties from intersected objects.

### LINKED ISSUE #64: Schema for intersection types are invalid
Given:

```typescript
const schema1 = z.object({
    foo: z.string()
});
const schema2= z.object({
    bar: z.string()
});
const intersection = z.intersection(schema1, schema2);
const jsonSchema = parseIntersectionDef(intersection._def, getRefs());
```

the following schema is generated:

```json
{
    "allOf": [
        {
            "additionalProperties": false,
            "properties": {
                "foo": {
                    "type": "string"
                }
            },
            "required": [
                "foo"
            ],
            "type": "object"
        },
        {
            "additionalProperties": false,
            "properties": {
                "bar": {
                    "type": "string"
                }
            },
            "required": [
                "bar"
            ],
            "type": "object"
        }
    ]
}
```

The following input:

```typescript
{ foo: 'foo', bar: 'bar' }
```

results in an validation error:

image

The Problem is, that the `additionalProperties` in both `allOf`-schemas resullts in failing each separate sub-schema validation. This seems to be a [common problem in JsonSchema-Validation](https://stackoverflow.com/a/23001194/1666829).

The JSON-Schema which is validating everything as expected looks like:

```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "required": [
        "foo"
      ],
    },
    {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      },
      "required": [
        "bar"
      ],
    }
  ],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "unevaluatedProperties": false
}
```

Note the `unevaluatedProperties` and the missing `additionalProperties`.

image

This issue was found in https://github.com/backstage/backstage/issues/17721

### PR DESCRIPTION
**Pull request by Andy2003**
resolves #64

### CODE REVIEW

File: src/parsers/intersection.ts [hunk 1]
```diff
@@ -19,7 +20,16 @@ export function parseIntersectionDef(
...
+        const {additionalProperties, ...rest} = schema;
+        return {
+          ...rest
+        };
+      }
+      return schema
+    });
 
-  return allOf.length ? { allOf } : undefined;
+  return allOf.length ? {allOf, unevaluatedProperties: false} : undefined;
```
Comment (StefanTerdell) [inline src/parsers/intersection.ts:34]: Only set this to false if the conditional on line 25 kicks in. You could instantiate it as undefined beforehand and set it to false in the if-statement, for instance

**Review by StefanTerdell — CHANGES_REQUESTED** [review]

File: src/parsers/intersection.ts (hunk 1 above)
Comment (StefanTerdell) [reply src/parsers/intersection.ts:34]: Actually I guess all of the object schemas should have additionalProperties set to false for this to apply

File: src/parsers/intersection.ts [hunk 2]
```diff
@@ -21,5 +28,36 @@ export function parseIntersectionDef(
...
+        // As soon as one of the schemas has additionalProperties set not to false, we allow unevaluatedProperties
+        unevaluatedProperties = undefined;
+      }
+      mergedAllOf.push(nestedSchema);
+
+    }
+  });
+  return mergedAllOf.length ? {
+    allOf: mergedAllOf,
+    ...unevaluatedProperties
```
Comment (Andy2003) [inline src/parsers/intersection.ts:61]: @StefanTerdell the `unevaluatedProperties` property was introduced in JsonSchema `2019-09`, but this library is generating `Draft-7`. Should we upgrade to `2019-09` or should I remove this new field?

**Review by StefanTerdell — APPROVED** [review]
